AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  FunctionalMethods:
    - expect

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-capybara
  - rubocop-rspec
