source 'http://rubygems.org'

ruby '3.4.1'

gem 'async'
gem 'discordrb'
gem 'ed25519'
gem 'grape'
gem 'grape-roar', '>= 0.4.0'
gem 'grape-swagger'
gem 'hashie'
gem 'httparty'
gem 'irb'
gem 'kaminari-grape'
gem 'mongoid'
gem 'mongoid-locker'
gem 'mongoid-scroll'
gem 'newrelic_rpm'
gem 'open-weather-ruby-client'
gem 'ostruct'
gem 'polylines'
gem 'puma'
gem 'rack', '~> 3.0.0'
gem 'rack-cors'
gem 'rack-rewrite'
gem 'rack-robotz'
gem 'rack-server-pages'
gem 'ruby-enum'
gem 'strava-ruby-client', '~> 2.2.0'
gem 'stripe', '~> 1.58.0'
gem 'wannabe_bool'

group :development, :test do
  gem 'foreman'
  gem 'rackup'
  gem 'rake', '~> 12.3'
  gem 'rubocop'
  gem 'rubocop-capybara'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
end

group :development do
  gem 'mongoid-shell'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner-mongoid'
  gem 'fabrication'
  gem 'faker'
  gem 'faraday-rack'
  gem 'hyperclient'
  gem 'rack-test'
  gem 'rspec'
  gem 'selenium-webdriver'
  gem 'stripe-ruby-mock', '~> 2.4.1', require: 'stripe_mock'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
  gem 'webrick'
end
